# fly.toml app configuration file generated for racket-eval-bot.
#
# See https://fly.io/docs/reference/configuration/ for information
# about how to use this file.
#

app = "racket-eval-bot"
primary_region = "hkg"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
