name: Test
on: [push, pull_request]
jobs:
  build:
    name: "Test on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["8.11"]
        racket-variant: ["CS"]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Bogdanp/setup-racket@v1.9.1
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing telebot
        run: raco pkg install --no-docs --auto --link telebot
      - name: Testing telebot
        run: raco test -x -p telebot
      - name: Installing eval-bot
        run: raco pkg install --no-docs --auto --link eval-bot
      - name: Testing eval-bot
        run: raco test -x -p eval-bot
